apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: korda-rag-stage-kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: korda-rag
  source:
    repoURL: https://kyverno.github.io/kyverno
    chart: kyverno
    targetRevision: 3.2.7
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
