apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: korda-rag-stage-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: korda-rag
  source:
    repoURL: https://github.com/Matt-Harrington1650/KORDA-RAG.git
    targetRevision: HEAD
    path: deploy/policies/network/stage
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-stage